CREATE SEQUENCE IF NOT EXISTS game_event_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE game
(
    game_id    UUID                        NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    status     VARCHAR(20),
    winner_id  UUID,
    CONSTRAINT pk_game PRIMARY KEY (game_id)
);

CREATE TABLE game_event
(
    id              BIGINT NOT NULL,
    game_id         UUID   NOT NULL,
    player_id       UUID   NOT NULL,
    round_id        BIGINT NOT NULL,
    sequence_number INTEGER,
    draw_type       VARCHAR(255),
    action_data     JSONB,
    CONSTRAINT pk_gameevent PRIMARY KEY (id)
);

CREATE TABLE game_participants
(
    game_id UUID NOT NULL,
    user_id UUID NOT NULL,
    CONSTRAINT pk_game_participants PRIMARY KEY (game_id, user_id)
);

CREATE TABLE game_rounds
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    game_id        UUID                                    NOT NULL,
    round_number   INTEGER,
    initial_deck   JSONB,
    starting_hands JSONB,
    status         VARCHAR(20),
    CONSTRAINT pk_game_rounds PRIMARY KEY (id)
);

CREATE TABLE round_score
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    round_id  BIGINT                                  NOT NULL,
    player_id UUID                                    NOT NULL,
    score     INTEGER                                 NOT NULL,
    CONSTRAINT pk_round_score PRIMARY KEY (id)
);

CREATE TABLE "user"
(
    player_id  UUID                        NOT NULL,
    username   VARCHAR(255)                NOT NULL,
    last_login TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (player_id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_username UNIQUE (username);

ALTER TABLE game_event
    ADD CONSTRAINT FK_GAMEEVENT_ON_GAME FOREIGN KEY (game_id) REFERENCES game (game_id);

ALTER TABLE game_event
    ADD CONSTRAINT FK_GAMEEVENT_ON_PLAYER FOREIGN KEY (player_id) REFERENCES "user" (player_id);

ALTER TABLE game_event
    ADD CONSTRAINT FK_GAMEEVENT_ON_ROUND FOREIGN KEY (round_id) REFERENCES game_rounds (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_WINNER FOREIGN KEY (winner_id) REFERENCES "user" (player_id);

ALTER TABLE game_participants
    ADD CONSTRAINT FK_GAME_PARTICIPANTS_ON_GAME FOREIGN KEY (game_id) REFERENCES game (game_id);

ALTER TABLE game_participants
    ADD CONSTRAINT FK_GAME_PARTICIPANTS_ON_USER FOREIGN KEY (user_id) REFERENCES "user" (player_id);

ALTER TABLE game_rounds
    ADD CONSTRAINT FK_GAME_ROUNDS_ON_GAME FOREIGN KEY (game_id) REFERENCES game (game_id);

ALTER TABLE round_score
    ADD CONSTRAINT FK_ROUND_SCORE_ON_PLAYER FOREIGN KEY (player_id) REFERENCES "user" (player_id);

ALTER TABLE round_score
    ADD CONSTRAINT FK_ROUND_SCORE_ON_ROUND FOREIGN KEY (round_id) REFERENCES game_rounds (id);